### ISSUE TITLE
Sweep: Increase the performance of KOT class functions in src/kot/kot.py

### ISSUE THREAD

**Issue by onuratakan** [onuratakan/KOT#166]
<details>
<summary>Checklist</summary>

- [X] `src/kot/kot.py">
* Optimize the `set` function by removing unnecessary operations and improving execution time.
* Enhance the `get` function to retrieve values more efficiently and reduce time complexity.
* Improve the `delete` function to optimize the deletion process and minimize execution time.
* Implement caching mechanisms to store frequently accessed key-value pairs.
* Evaluate and optimize the usage of compression and encryption in the `KOT` class.
</modify>

<modify file="tests/unit_tests.py`
> * Update unit tests to verify the improved performance of the `set`, `get`, and `delete` functions.

</details>

**Comment by kevinlu1248** [comment]
@onuratakan This issue should be fixed. Can you provide more details for this issue though?
